spring:
  application:
    name: url-shortener-api
  redis:
    lettuce:
      pool:
        max-active: 600
        max-idle: 50
        min-idle: 5
        max-wait: -1ms
      shutdown-timeout: 100ms
    host: ${URL_SHORTENER_REDIS_HOST}
    password: $12E45
    port: ${URL_SHORTENER_REDIS_PORT}
    ssl: false
    timeout: 5000ms
  cache:
    type: redis

    
